/*
Repeat your program from the previous exercise, but this time store `shared_ptr`s
to objects of type `Quote`. Explain any discrepancy in the sum generated by this
version and the version from the previous program. 
*/

// The discrepancy is because this version uses a pointer (as it happens, shared_ptr),
// which along with references are the two types that support polymorphism in C++.
// As a result, the Bulk_quote object is not sliced down when added to the vector,
// and remains intact, with the net_price method being overridden. 

#include <iostream>
#include <string>
#include <cstddef>
#include <vector>
#include <memory>

class Quote {
    public:
        Quote() = default;
        Quote(const std::string &book, double sales_price):
            bookNo(book), price(sales_price) { }
        std::string isbn() const { return bookNo; }
        virtual double net_price(std::size_t n) const { return n * price; }
        virtual ~Quote() = default;
    private:
        std::string bookNo;
    protected:
        double price = 0.0;
};

// double print_total(std::ostream& os, const Quote &item, std::size_t n) {
//     double ret = item.net_price(n);
//     os << "ISBN: " << item.isbn() 
//         << " # sold: " << n 
//         << " Total due: " << ret 
//         << std::endl;
//     return ret;
// }

class Disc_quote : public Quote {
public:
    Disc_quote() = default;
    Disc_quote(const std::string& book, double price, std::size_t qty, double disc):
        Quote(book, price), quantity(qty), discount(disc) { }
    double net_price(std::size_t) const = 0;
protected:
    std::size_t quantity = 0;
    double discount = 0.0;
};

class Bulk_quote : public Disc_quote {
public:
    using Disc_quote::Disc_quote;
    // Bulk_quote() = default;
    // Bulk_quote(const std::string& book, double price, std::size_t qty, double disc):
    //     Disc_quote(book, price, qty, disc) { }
    double net_price(std::size_t n) const override {
        if (n >= quantity)
            return (1 - discount) * n * price;
        else
            return n * price;
    }
};

int main() {
    // will NOT get sliced down, and base class net_price will NOT used.
    std::vector<std::shared_ptr<Quote>> qvec;
    qvec.push_back(
        std::make_shared<Bulk_quote>("The C++ Primer (Fifth Edition)", 69.99, 10, 0.25)
    );
    for (const auto &item : qvec)
        std::cout << item->net_price(11) << std::endl;

    return 0;
}